/** @format */

import type {Metadata} from 'next';
import {Toaster} from '@/components/ui/toaster';
import {Inter} from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import {ThemeProvider} from '@/components/theme-provider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Blogsite | Kenapa Coding',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang='en'>
      <body className={inter.className}>
      <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Header/>
          <div className='p-8 md:px-28'>{children}</div>
          <Toaster/>
      </ThemeProvider>
      </body>
      </html>
  );
}